name: Break Tracker CI
on:
  push:
  pull_request:

jobs:
  api:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install backend deps
        working-directory: backend
        run: npm i --no-audit --no-fund

      - name: Start backend
        working-directory: backend
        env:
          PORT: 3001
          JWT_SECRET: testsecret
        run: |
          node server.js & echo $! > server.pid
          for i in {1..30}; do
            curl -fsS http://localhost:3001/api/health && break
            sleep 1
          done

      - name: Health check
        run: |
          curl -fsS http://localhost:3001/api/health | tee health.json
          grep -q '"status":"ok"' health.json

      - name: Login (admin/admin123)
        run: |
          curl -fsS -H "Content-Type: application/json" \
            -d '{"username":"admin","password":"admin123"}' \
            http://localhost:3001/api/auth/login | tee login.json
          grep -q '"token"' login.json
          echo "ADMIN_TOKEN=$(node -p "JSON.parse(require('fs').readFileSync('login.json','utf8')).token")" >> $GITHUB_ENV

      - name: Create department
        env:
          ADMIN_TOKEN: ${{ env.ADMIN_TOKEN }}
        run: |
          DNAME="CI Dept $GITHUB_RUN_NUMBER"
          curl -fsS -H "Authorization: Bearer $ADMIN_TOKEN" -H "Content-Type: application/json" \
            -d "{\"name\":\"$DNAME\"}" \
            http://localhost:3001/api/departments | tee dep.json
          grep -q '"id":' dep.json
          echo "DEP_ID=$(node -p "JSON.parse(require('fs').readFileSync('dep.json','utf8')).id")" >> $GITHUB_ENV

      - name: Create team (auto-pick department)
        env:
          ADMIN_TOKEN: ${{ env.ADMIN_TOKEN }}
        run: |
          TNAME="CI Team $GITHUB_RUN_NUMBER"
          curl -fsS -H "Authorization: Bearer $ADMIN_TOKEN" -H "Content-Type: application/json" \
            -d "{\"name\":\"$TNAME\"}" \
            http://localhost:3001/api/teams | tee team.json
          grep -q '"id":' team.json
          echo "TEAM_ID=$(node -p "JSON.parse(require('fs').readFileSync('team.json','utf8')).id")" >> $GITHUB_ENV

      - name: Create break type
        env:
          ADMIN_TOKEN: ${{ env.ADMIN_TOKEN }}
        run: |
          BNAME="CI Break $GITHUB_RUN_NUMBER"
          curl -fsS -H "Authorization: Bearer $ADMIN_TOKEN" -H "Content-Type: application/json" \
            -d "{\"name\":\"$BNAME\",\"color\":\"#ccc\"}" \
            http://localhost:3001/api/break-types | tee bt.json
          grep -q '"id":' bt.json
          echo "BT_ID=$(node -p "JSON.parse(require('fs').readFileSync('bt.json','utf8')).id")" >> $GITHUB_ENV

      - name: Start & Stop break as admin
        env:
          ADMIN_TOKEN: ${{ env.ADMIN_TOKEN }}
          BT_ID: ${{ env.BT_ID }}
        run: |
          curl -fsS -H "Authorization: Bearer $ADMIN_TOKEN" -H "Content-Type: application/json" \
            -d "{\"break_type_id\":$BT_ID}" \
            http://localhost:3001/api/breaks/start | tee start.json
          grep -q '"id":' start.json

          curl -fsS -H "Authorization: Bearer $ADMIN_TOKEN" -H "Content-Type: application/json" \
            -d "{}" \
            http://localhost:3001/api/breaks/stop | tee stop.json
          grep -q '"success":true' stop.json

      - name: Create user (no password -> must_change_password)
        env:
          ADMIN_TOKEN: ${{ env.ADMIN_TOKEN }}
        run: |
          U="ciuser_$GITHUB_RUN_NUMBER"
          curl -fsS -H "Authorization: Bearer $ADMIN_TOKEN" -H "Content-Type: application/json" \
            -d "{\"username\":\"$U\",\"name\":\"CI User\"}" \
            http://localhost:3001/api/users | tee user.json
          grep -q '"id":' user.json
          echo "NEWUSER=$U" >> $GITHUB_ENV
          echo "NEWUSER_ID=$(node -p "JSON.parse(require('fs').readFileSync('user.json','utf8')).id")" >> $GITHUB_ENV

      - name: Create employee for new user (link to dept/team)
        env:
          ADMIN_TOKEN: ${{ env.ADMIN_TOKEN }}
          NEWUSER_ID: ${{ env.NEWUSER_ID }}
          DEP_ID: ${{ env.DEP_ID }}
          TEAM_ID: ${{ env.TEAM_ID }}
        run: |
          curl -fsS -H "Authorization: Bearer $ADMIN_TOKEN" -H "Content-Type: application/json" \
            -d "{\"user_id\":$NEWUSER_ID,\"name\":\"CI Employee\",\"department_id\":$DEP_ID,\"team_id\":$TEAM_ID}" \
            http://localhost:3001/api/employees | tee emp.json
          grep -q '"id":' emp.json
          echo "EMP_ID=$(node -p "JSON.parse(require('fs').readFileSync('emp.json','utf8')).id")" >> $GITHUB_ENV

      - name: Login as new user with default password
        env:
          NEWUSER: ${{ env.NEWUSER }}
        run: |
          curl -fsS -H "Content-Type: application/json" \
            -d "{\"username\":\"$NEWUSER\",\"password\":\"ChangeMe123!\"}" \
            http://localhost:3001/api/auth/login | tee ulogin.json
          grep -q '"token"' ulogin.json
          echo "USER_TOKEN=$(node -p "JSON.parse(require('fs').readFileSync('ulogin.json','utf8')).token")" >> $GITHUB_ENV

      - name: Change new user password
        env:
          USER_TOKEN: ${{ env.USER_TOKEN }}
        run: |
          curl -fsS -H "Authorization: Bearer $USER_TOKEN" -H "Content-Type: application/json" \
            -d "{\"current_password\":\"ChangeMe123!\",\"new_password\":\"NewCIPass123!\"}" \
            http://localhost:3001/api/auth/change-password | tee cp.json
          grep -q '"success":true' cp.json

      - name: Re-login with new password
        env:
          NEWUSER: ${{ env.NEWUSER }}
        run: |
          curl -fsS -H "Content-Type: application/json" \
            -d "{\"username\":\"$NEWUSER\",\"password\":\"NewCIPass123!\"}" \
            http://localhost:3001/api/auth/login | tee ulogin2.json
          grep -q '"token"' ulogin2.json
          echo "USER2_TOKEN=$(node -p "JSON.parse(require('fs').readFileSync('ulogin2.json','utf8')).token")" >> $GITHUB_ENV

      - name: Start live break as new user
        env:
          USER2_TOKEN: ${{ env.USER2_TOKEN }}
          BT_ID: ${{ env.BT_ID }}
        run: |
          curl -fsS -H "Authorization: Bearer $USER2_TOKEN" -H "Content-Type: application/json" \
            -d "{\"break_type_id\":$BT_ID}" \
            http://localhost:3001/api/breaks/start | tee start2.json
          grep -q '"id":' start2.json

      - name: Check live status includes this employee
        env:
          ADMIN_TOKEN: ${{ env.ADMIN_TOKEN }}
          EMP_ID: ${{ env.EMP_ID }}
        run: |
          curl -fsS -H "Authorization: Bearer $ADMIN_TOKEN" \
            http://localhost:3001/api/status/live | tee live.json
          node -e "const a=JSON.parse(require('fs').readFileSync('live.json','utf8')); if(!Array.isArray(a)||!a.find(x=>x.employee_id==process.env.EMP_ID)) throw new Error('employee not in live status');"

      - name: Stop that live break
        env:
          USER2_TOKEN: ${{ env.USER2_TOKEN }}
        run: |
          curl -fsS -H "Authorization: Bearer $USER2_TOKEN" -H "Content-Type: application/json" \
            -d "{}" \
            http://localhost:3001/api/breaks/stop | tee stop2.json
          grep -q '"success":true' stop2.json

      - name: Usage report by employee (should include the new employee)
        env:
          ADMIN_TOKEN: ${{ env.ADMIN_TOKEN }}
          EMP_ID: ${{ env.EMP_ID }}
        run: |
          curl -fsS -H "Authorization: Bearer $ADMIN_TOKEN" \
            "http://localhost:3001/api/reports/usage?group=employee" | tee rep.json
          node -e "const a=JSON.parse(require('fs').readFileSync('rep.json','utf8')); if(!Array.isArray(a)||!a.find(x=>x.employee_id==process.env.EMP_ID)) throw new Error('employee missing from report');"

      - name: Stop backend
        if: always()
        working-directory: backend
        run: kill -9 $(cat server.pid) || true
