name: Break Tracker CI
on:
  push:
  pull_request:
jobs:
  api:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: backend/package-lock.json
      - name: Install backend deps
        working-directory: backend
        run: npm ci || npm i --no-audit --no-fund
      - name: Start backend
        working-directory: backend
        env:
          PORT: 3001
          JWT_SECRET: testsecret
          NODE_ENV: test
        run: |
          node server.js & echo $! > server.pid
          npx --yes wait-on http-get://localhost:3001/api/health
      - name: Run API tests
        working-directory: backend
        env:
          BASE_URL: http://localhost:3001
          ADMIN_USER: admin
          ADMIN_PASS: admin123
          NEW_ADMIN_PASS: admin1234!
        run: npm test -- --runInBand
      - name: Stop backend
        if: always()
        working-directory: backend
        run: |
          kill -9 $(cat server.pid) || true
